### ISSUE TITLE
Unable to simulate Frida APP

### ISSUE THREAD

**Issue by moosman1** [IBM/Frida#22]
Hi Team,

I tried simulating the Frida app. I have pushed the frida backend to Ibm cloud as per the steps. Looks like some DB setup is needed. Can you please share the updated Frida backend repo. The below is the error :

![image](https://user-images.githubusercontent.com/20779335/62027244-d1b8cb80-b1fa-11e9-8c50-fd257ca2844b.png)

**Comment by krook** [comment]
@LinJu @iSimar ^^^

**Comment by LinJu** [comment]
@yasinghcse will update with detail soon!

**Comment by yasinghcse** [comment]
@moosman1 Can you pull the latest changes from https://github.com/IBM/Frida-app and try to run the App again? 
We have pushed the change which will enable you to run the App without DB connectivity. Currently, DB is only required for maintaining user information.

**Comment by moosman1** [comment]
Hi Yad,
I am able to simulate it now but with few warnings/errors (may be package dependencies). I have few other queries & will reach out to you. Thank you so much for this.
