### ISSUE TITLE
Readme doesn't contain setup instructions

### ISSUE THREAD

**Issue by derekteay** [IBM/Frida#6]
The readme should explain requirements, pre-requisites, and/or instructions for standing up the code

**Comment by LinJu** [comment]
@derekteay We have setup instruction for different areas include sensors, application, server. Do you think it is good idea to put into wiki instead of readme?

**Comment by LinJu** [comment]
@derekteay We have stand up 5 repos and each repo will have readme which contain detail instruction and information for those repos. 

- [x]  [Frida](https://github.com/IBM/Frida) 
- [x] [Frida-APP](https://github.com/IBM/Frida-APP)
- [x] [Frida-backend](https://github.com/IBM/Frida-backend)
- [x] [Frida-ML](https://github.com/IBM/Frida-ML)
- [x] [Frida-IoT](https://github.com/IBM/Frida-IoT)
